In [1]:
# Import torch and other required modules

import tensorflow as tf

In [2]:
# shape

In [3]:
#scalar
a=tf.random.uniform(shape=[1], minval=5, maxval=10, dtype=tf.int64)
print(a)

tf.Tensor([8], shape=(1,), dtype=int64)


In [4]:
#vector
a=tf.random.uniform(shape=[2], minval=5, maxval=10, dtype=tf.int64)
print(a)

tf.Tensor([9 9], shape=(2,), dtype=int64)


In [5]:
#matrix
a=tf.random.uniform(shape=[2,2], minval=5, maxval=10, dtype=tf.int64)
print(a)

tf.Tensor(
[[6 9]
 [9 5]], shape=(2, 2), dtype=int64)


In [6]:
#tensor n*n*n matrix
a=tf.random.uniform(shape=[2,2,2], minval=5, maxval=10, dtype=tf.int64)
print(a)

tf.Tensor(
[[[9 6]
  [6 7]]

 [[5 6]
  [9 9]]], shape=(2, 2, 2), dtype=int64)


# simple operation using tensorflow

In [7]:
# Get the rank of the tensor
tensorA = tf.constant([[1, 2], [3, 4], [5, 6]]);
rank = tf.rank(tensorA)
print(rank)

tf.Tensor(2, shape=(), dtype=int32)


ALL bascic arthemathic opertation

In [8]:
a = tf.constant(2)
b = tf.constant(3)


In [9]:

# Addition
c = tf.add(a, b)

print(c)


tf.Tensor(5, shape=(), dtype=int32)


In [10]:
# Subtraction
d = tf.subtract(a, b)
print(d)

tf.Tensor(-1, shape=(), dtype=int32)


In [11]:
# Multiplication
e = tf.multiply(a, b)
print(e)

tf.Tensor(6, shape=(), dtype=int32)


In [12]:
# Division
f = tf.divide(a, b)
print(f)

tf.Tensor(0.6666666666666666, shape=(), dtype=float64)


In [13]:
#Tensor Addition
tensorA = tf.constant([[1, 2], [3, 4], [5, 6]]);
tensorB = tf.constant([[1,-1], [2,-2], [3,-3]]);

tensorNew = tf.add(tensorA,tensorB)

print(tensorNew)

tf.Tensor(
[[2 1]
 [5 2]
 [8 3]], shape=(3, 2), dtype=int32)


In [14]:
#Tensor Subtraction
tensorA = tf.constant([[1, 2], [3, 4], [5, 6]]);
tensorB = tf.constant([[1,-1], [2,-2], [3,-3]]);


tensorNew = tf.subtract(tensorA,tensorB);
print(tensorNew)


tf.Tensor(
[[0 3]
 [1 6]
 [2 9]], shape=(3, 2), dtype=int32)


In [15]:
#Tensor Multiplication
tensorA = tf.constant([1, 2, 3, 4]);
tensorB = tf.constant([4, 4, 2, 2]);


tensorNew = tf.multiply(tensorA,tensorB)
print(tensorNew)

tf.Tensor([4 8 6 8], shape=(4,), dtype=int32)


In [16]:
#Tensor Multiplication
#this not matrix multiplication its element wise multiplication
tensorA = tf.constant([[1, 2], [3, 4]]);
tensorB = tf.constant([[1,-1], [2,-2]]);


tensorNew = tf.multiply(tensorA,tensorB)
print(tensorNew)

tf.Tensor(
[[ 1 -2]
 [ 6 -8]], shape=(2, 2), dtype=int32)


In [17]:
#Tensor Division
tensorA = tf.constant([2, 4, 6, 8]);
tensorB = tf.constant([1, 2, 2, 2]);


tensorNew = tf.divide(tensorA, tensorB);
print(tensorNew)

tf.Tensor([2. 2. 3. 4.], shape=(4,), dtype=float64)


tensor reshape

In [18]:
tensorA = tf.constant([[1, 2], [3, 4]]);
tensorB = tf.reshape(tensorA,[4, 1]);
print(tensorB )

tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)


In [34]:
tensorA = tf.constant([[1, 2], [3, 4]]);
tensorB = tf.reshape(tensorA,[1,4]);
print(tensorB )

tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


# variable and constand

VARIABLE
TensorFlow variables are typically used to store model parameters, such as weights and biases, which are adjusted during the training process to improve model performance. In other words, variables are used to store values that change during the execution of the graph.

For example, in a neural network model, the weights and biases are adjusted during the training process to minimize the loss function. We can use TensorFlow variables to store these values and update them during each iteration of the training process

In [20]:
# Create a variable tensor
b = tf.Variable([4, 5, 6])
#In the above code, b is a variable tensor with initial values [4, 5, 6]. 
#Unlike constants, variables can be modified using operations like assignment (tf.assign()) or 
#through the training process by optimizers.

CONSTAND
TensorFlow constants are typically used to store input data or other fixed values that are used in the model. In other words, constants are used to store values that remain constant throughout the execution of the graph.

In [21]:
# Create a constant tensor
a = tf.constant([1, 2, 3])
#In the above code, a is a constant tensor with values [1, 2, 3]. 
#The values of constants cannot be modified once they are defined.

We saw that TensorFlow variables are used to store values that change during the execution of the graph,
such as model parameters and stateful operations, while TensorFlow constants are used to store values that remain constant throughout the execution of the graph, 
such as input data and other fixed values.

In [ ]:
# creating a placeholder
a = tf.placeholder(tf.float32, None)

#loss functions

Categorical crossentropy is a commonly used loss function in multi-class classification tasks. 
It measures the dissimilarity between the predicted probability distribution and the true one-hot encoded labels.

Sparse categorical crossentropy is a loss function commonly used in multi-class classification tasks where the true labels are integers instead of one-hot encoded vectors. 
It computes the crossentropy loss between the predicted probability distribution and the true integer labels.


Kullback-Leibler (KL) divergence, also known as relative entropy, is a measure of the difference between two probability distributions. 
In the context of machine learning, it is often used as a loss function to compare predicted probability distributions
with true probability distributions.

Regression Tasks:

Mean Squared Error (MSE): Measures the average squared difference between predicted and true values.
Mean Absolute Error (MAE): Computes the average absolute difference between predicted and true values.
Huber Loss: Combines the advantages of MSE and MAE, providing a more robust loss function that is less sensitive to outliers.
Binary Classification:

Binary Crossentropy: Measures the dissimilarity between the predicted probabilities and the true binary labels.
Hinge Loss: Suitable for SVM-based classifiers, penalizes misclassified samples.
Log Loss: Computes the logarithm of the predicted probabilities for binary classification tasks.
Multi-class Classification:

Categorical Crossentropy: Evaluates the difference between predicted probabilities and true class labels for multi-class classification.
Sparse Categorical Crossentropy: Similar to categorical crossentropy, but expects integer target labels instead of one-hot encoded vectors.
Kullback-Leibler Divergence: Measures the divergence between predicted and true probability distributions.
Sequence Generation:

Connectionist Temporal Classification (CTC) Loss: Used for tasks like speech recognition, it handles variable-length sequences and alignment between inputs and targets.
Object Detection:

Intersection over Union (IoU): Measures the overlap between predicted and true bounding boxes.
Mean Average Precision (mAP): Evaluates the precision and recall of object detection models.

In [22]:
#OPTIMZER

In [26]:
import tensorflow_datasets as tfds
from tensorflow.keras.utils import to_categorical

## Loading images and labels
(train_ds, train_labels), (test_ds, test_labels) = tfds.load(
    "tf_flowers",
    split=["train[:70%]", "train[:30%]"], ## Train test split
    batch_size=-1,
    as_supervised=True,  # Include labels
)

## Resizing images
train_ds = tf.image.resize(train_ds, (150, 150))
test_ds = tf.image.resize(test_ds, (150, 150))

## Transforming labels to correct format
train_labels = to_categorical(train_labels, num_classes=5)
test_labels = to_categorical(test_labels, num_classes=5)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\91964\tensorflow_datasets\tf_flowers\3.0.1.incompleteU2SQF0\tf_flowers-train.tfrecord*...: …

Dataset tf_flowers downloaded and prepared to C:\Users\91964\tensorflow_datasets\tf_flowers\3.0.1. Subsequent calls will reuse this data.


In [27]:
#https://www.geeksforgeeks.org/vgg-16-cnn-model/
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input

## Loading VGG16 model
base_model = VGG16(weights="imagenet", include_top=False, input_shape=train_ds[0].shape)
base_model.trainable = False ## Not trainable weights

## Preprocessing input
train_ds = preprocess_input(train_ds) 
test_ds = preprocess_input(test_ds)

58889256/58889256 [==============================] - 6s 0us/step


In [28]:
base_model.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 150, 150, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 150, 150, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 150, 150, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 75, 75, 64)        0         
                                                                 
 block2_conv1 (Conv2D)       (None, 75, 75, 128)       73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 75, 75, 128)       147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 37, 37, 128)       0     

In [29]:
from tensorflow.keras import layers, models

flatten_layer = layers.Flatten()
dense_layer_1 = layers.Dense(50, activation='relu')
dense_layer_2 = layers.Dense(20, activation='relu')
prediction_layer = layers.Dense(5, activation='softmax')


model = models.Sequential([
    base_model,
    flatten_layer,
    dense_layer_1,
    dense_layer_2,
    prediction_layer
])

In [31]:
from tensorflow.keras.callbacks import EarlyStopping

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'],
)


es = EarlyStopping(monitor='val_accuracy', mode='max', patience=5,  restore_best_weights=True)

model.fit(train_ds, train_labels, epochs=5, validation_split=0.2, batch_size=32, callbacks=[es])


Epoch 1/5
65/65 [==============================] - 556s 9s/step - loss: 0.8868 - accuracy: 0.6818 - val_loss: 0.9846 - val_accuracy: 0.6518
Epoch 2/5
65/65 [==============================] - 535s 8s/step - loss: 0.6035 - accuracy: 0.7766 - val_loss: 1.0780 - val_accuracy: 0.6693
Epoch 3/5
65/65 [==============================] - 540s 8s/step - loss: 0.4015 - accuracy: 0.8477 - val_loss: 0.9721 - val_accuracy: 0.6732
Epoch 4/5
65/65 [==============================] - 555s 9s/step - loss: 0.3334 - accuracy: 0.8706 - val_loss: 0.9676 - val_accuracy: 0.7004
Epoch 5/5
65/65 [==============================] - 503s 8s/step - loss: 0.2278 - accuracy: 0.9148 - val_loss: 1.0065 - val_accuracy: 0.7160


In [33]:
# #hands on image classification
# from tensorflow.keras import Sequential, layers
# from tensorflow.keras.callbacks import EarlyStopping
# from tensorflow.keras.layers.experimental.preprocessing import Rescaling


# hand_made_model = Sequential()
# hand_made_model.add(Rescaling(1./255, input_shape=(150,150,3)))

# hand_made_model.add(layers.Conv2D(16, kernel_size=10, activation='relu'))
# hand_made_model.add(layers.MaxPooling2D(3))

# hand_made_model.add(layers.Conv2D(32, kernel_size=8, activation="relu"))
# hand_made_model.add(layers.MaxPooling2D(2))

# hand_made_model.add(layers.Conv2D(32, kernel_size=6, activation="relu"))
# hand_made_model.add(layers.MaxPooling2D(2))

# hand_made_model.add(layers.Flatten())
# hand_made_model.add(layers.Dense(50, activation='relu'))
# hand_made_model.add(layers.Dense(20, activation='relu'))
# hand_made_model.add(layers.Dense(5, activation='softmax'))


# hand_made_model.compile(
#     optimizer='adam',
#     loss='categorical_crossentropy',
#     metrics=['accuracy'],
# )


# es = EarlyStopping(monitor='val_accuracy', mode='max', patience=5,  restore_best_weights=True)

# hand_made_model.fit(train_ds, train_labels, epochs=5, validation_split=0.2, batch_size=32, callbacks=[es])


Epoch 1/5
65/65 [==============================] - 77s 1s/step - loss: 1.5236 - accuracy: 0.3114 - val_loss: 1.3706 - val_accuracy: 0.4261
Epoch 2/5
65/65 [==============================] - 67s 1s/step - loss: 1.3236 - accuracy: 0.4209 - val_loss: 1.2906 - val_accuracy: 0.4163
Epoch 3/5
65/65 [==============================] - 75s 1s/step - loss: 1.2150 - accuracy: 0.4827 - val_loss: 1.1854 - val_accuracy: 0.4922
Epoch 4/5
65/65 [==============================] - 69s 1s/step - loss: 1.1296 - accuracy: 0.5275 - val_loss: 1.2471 - val_accuracy: 0.4747
Epoch 5/5
65/65 [==============================] - 79s 1s/step - loss: 1.0806 - accuracy: 0.5509 - val_loss: 1.1140 - val_accuracy: 0.5292


In [36]:
test_loss, test_accuracy = model.evaluate(test_ds, test_labels)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

35/35 [==============================] - 324s 9s/step - loss: 0.1865 - accuracy: 0.9373
Test Loss: 0.18648457527160645
Test Accuracy: 0.9373297095298767


<tf.Tensor: shape=(1101, 150, 150, 3), dtype=float32, numpy=
array([[[[-6.84166870e+01,  1.53410110e+01, -1.78466644e+01],
         [-6.15640678e+01,  2.19140701e+01, -8.05359650e+00],
         [-7.29496689e+01,  8.33789062e+00, -2.39697800e+01],
         ...,
         [-1.03939003e+02, -1.16778999e+02, -1.23680000e+02],
         [-1.03939003e+02, -1.16778999e+02, -1.23680000e+02],
         [-1.03939003e+02, -1.16778999e+02, -1.23680000e+02]],

        [[-6.68862000e+01,  2.42730026e+01, -1.14402771e-01],
         [-4.53190041e+01,  3.26026077e+01,  9.54080963e+00],
         [-6.34483376e+01,  1.26169968e+01, -2.26906662e+01],
         ...,
         [-1.03939003e+02, -1.16778999e+02, -1.23680000e+02],
         [-1.03939003e+02, -1.16778999e+02, -1.23680000e+02],
         [-1.03939003e+02, -1.16778999e+02, -1.23680000e+02]],

        [[-7.64754486e+01,  2.28330002e+01,  3.30178070e+00],
         [-4.02803345e+01,  3.58623428e+01,  1.36720047e+01],
         [-5.20367775e+01,  2.55610123e

In [ ]:
import tensorflow as tf
print(tf.__version__)
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
#training_images=training_images/255.0
#test_images=test_images/255.0
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
model.fit(training_images, training_labels, epochs=5)
model.evaluate(test_images, test_labels)
classifications = model.predict(test_images)
print(classifications[0])
print(test_labels[0])